db-uri = "postgres://authenticator:FirstFeb2004@localhost:5432/str_gims"

db-schemas = "str_gims"

db-anon-role = "web_anon"

server-host = "!4"

server-port = 3000

openapi-mode = "follow-privileges"

db-channel = "pgrst"

db-channel-enabled = true